spring.application.name=sia-usd

# Server
server.port=8080

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Docker Compose integration
spring.docker.compose.lifecycle-management=start-and-stop

# Logging
logging.level.com.opeteer.spring_boot=INFO
